# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  gepaserverapresentation:
    image: gepaserverapresentation
    build:
      context: .
      dockerfile: Gepa.Server.Apresentation/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on: 
    - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    environment: 
    - PUID=1000
    - PGID=1000
    volumes: 
    - mongo-db:/data/db
    ports: 
    - 27017:27017
    restart: unless-stopped

volumes: 
  mongo-db: